[module]
[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.imports]]
path="github.com/gohugoio/hugo-mod-heroicons"
[[module.imports.mounts]]
source = "src"
target = "assets/svg/heroicons"